# Use an official Node.js runtime as a base image for building the React app
FROM node:16-alpine AS build

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install the frontend dependencies
RUN npm install

COPY .env .env

# Copy the rest of the application code
COPY . .

# Build the React app
RUN npm run build

# Use NGINX to serve the built files
FROM nginx:alpine

# Copy the built React files to NGINX's HTML folder
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 for the NGINX server
EXPOSE 80

# Run NGINX
CMD ["nginx", "-g", "daemon off;"]
