apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: booking-frontend
  template:
    metadata:
      labels:
        app: booking-frontend
    spec:
      containers:
      - name: booking-frontend
        image: 050752621233.dkr.ecr.eu-north-1.amazonaws.com/bcf/eticket:bookf
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://localhost:4001"
---
apiVersion: v1
kind: Service
metadata:
  name: booking-frontend
spec:
  type: LoadBalancer
  selector:
    app: booking-frontend
  ports:
  - port: 80
    targetPort: 80
