apiVersion: apps/v1
kind: Deployment
metadata:
  name: otp-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otp-frontend
  template:
    metadata:
      labels:
        app: otp-frontend
    spec:
      containers:
      - name: otp-frontend
        image: 050752621233.dkr.ecr.eu-north-1.amazonaws.com/bcf/otp-service-otp-frontend:v1
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://otp-backend:4002"
---
apiVersion: v1
kind: Service
metadata:
  name: otp-frontend
spec:
  type: LoadBalancer
  selector:
    app: otp-frontend
  ports:
  - port: 80
    targetPort: 80
