apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-info-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-info-frontend
  template:
    metadata:
      labels:
        app: train-info-frontend
    spec:
      containers:
      - name: train-info-frontend
        image: 050752621233.dkr.ecr.eu-north-1.amazonaws.com/bcf/eticket:trainf
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://train-info-backend:4000"
---
apiVersion: v1
kind: Service
metadata:
  name: train-info-frontend
spec:
  type: LoadBalancer
  selector:
    app: train-info-frontend
  ports:
  - port: 80
    targetPort: 80
