apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-frontend
  template:
    metadata:
      labels:
        app: user-frontend
    spec:
      containers:
      - name: user-frontend
        image: 050752621233.dkr.ecr.eu-north-1.amazonaws.com/bcf/user-service-user-frontend:v1
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://user-backend:3999"
---
apiVersion: v1
kind: Service
metadata:
  name: user-frontend
spec:
  type: LoadBalancer
  selector:
    app: user-frontend
  ports:
  - port: 80
    targetPort: 80
