# Use an official Node.js runtime as a base image
FROM node:16-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package*.json ./

# Install the backend dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port that the backend will run on
EXPOSE 4002

# Run the application
CMD ["npm", "start"]
